[mqtt]
broker = "broker.hivemq.com"
port = 1883
username = "smartbin"
password = "Smartbin66"
topic_subscribe = "smartbin/data"

[mongodb]
uri = "mongodb+srv://smartbin:smartbin66@cluster0.wqu4nqf.mongodb.net/?appName=Cluster0"
database = "smartbin"