[mqtt]
broker = "broker.hivemq.com"
port = 1883
username = "smartbin"
password = "Smartbin66"
topic_subscribe = "smartbin/data"

[mongodb]
uri = "mongodb+srv://adminirsyad:irsyad26@cluster0.ncfu3tp.mongodb.net/Sensor?retryWrites=true&w=majority&appName=SmartBinCluster"
database = "Sensor"